name: Deploy Backend

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to production server
      if: github.event.inputs.environment == 'production'
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.PRODUCTION_SERVER_USER }}@${{ secrets.PRODUCTION_SERVER_HOST }} << 'EOF'
          # 创建备份目录
          mkdir -p /opt/memos-backups/$(date +%Y%m%d-%H%M%S)

          # 停止服务
          sudo systemctl stop memos

          # 备份当前二进制文件
          sudo cp /opt/memos/memos-server /opt/memos-backups/$(date +%Y%m%d-%H%M%S)/

          # 下载新版本
          sudo wget -O /opt/memos/memos-server https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/memos-linux-amd64

          # 设置执行权限
          sudo chmod +x /opt/memos/memos-server

          # 启动服务
          sudo systemctl start memos

          # 检查服务状态
          sudo systemctl status memos
        EOF

    - name: Deploy to staging server
      if: github.event.inputs.environment == 'staging'
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_SERVER_USER }}@${{ secrets.STAGING_SERVER_HOST }} << 'EOF'
          # 创建备份目录
          mkdir -p /opt/memos-backups/$(date +%Y%m%d-%H%M%S)

          # 停止服务
          sudo systemctl stop memos

          # 备份当前二进制文件
          sudo cp /opt/memos/memos-server /opt/memos-backups/$(date +%Y%m%d-%H%M%S)/

          # 下载新版本
          sudo wget -O /opt/memos/memos-server https://github.com/${{ github.repository }}/releases/download/${{ github.event.release.tag_name }}/memos-linux-amd64

          # 设置执行权限
          sudo chmod +x /opt/memos/memos-server

          # 启动服务
          sudo systemctl start memos

          # 检查服务状态
          sudo systemctl status memos
        EOF
